var localizedStrings = new Array();

localizedStrings['nl_NL'] = new Array();
localizedStrings['de_DE'] = new Array();
localizedStrings['en_GB'] = new Array();
localizedStrings['fr_FR'] = new Array();
localizedStrings['es_ES'] = new Array();
localizedStrings['ru_RU'] = new Array();

localizedStrings['nl_NL'] = {
"Taal naam": "Nederlands",
"Springer": "Springer",
"Oefening": "Oefening",
"Jury": "Jury",
"Aftrek": "Aftrek",
"Score": "Score",
"ToF": "ToF",
"Sprong": "Sprong",
"Totaal": "Totaal",
"Algemeen": "Algemeen",
"Aanmelden": "Aanmelden",
"Upload": "Upload",
"Scorebord": "Scorebord",
"Extra aftrek": "Extra aftrek (werkelijke waarde)",
"Instellingen": "Instellingen",
"Algemene instellingen": "Algemene instellingen",
"Taal": "Taal",
"OK": "OK",
"Annuleren": "Annuleren",
"Opsturen": "Opsturen",
"Wedstrijd aanmelden": "Wedstrijd aanmelden",
"Scorebord instellingen": "Scorebord instellingen",
"Opgeslagen data": "Opgeslagen data",
"Wissen": "Wissen",
"Wedstrijd naam": "Wedstrijd naam",
"Wedstrijd nummer": "Wedstrijd nummer",
"Wachtwoord": "Wachtwoord",
"Score server": "Score server",
"Server log": "Server log",
"Jury naam": "Jury naam",
"Aanmaken": "Aanmaken",
"Inloggen": "Inloggen",
"Uitloggen": "Uitloggen",
"Deelnemers": "Deelnemers",
"Gebruik": "Gebruik",
"Automatische score upload": "Automatische score upload",
"Start timer": "Start timer",
"uit": "uit",
"aan": "aan",
"knop": "knop",
"automatisch": "automatisch",
"ja": "ja",
"nee": "nee",
"rechtshandig": "rechtshandig",
"Schermrotatie vastgezet": "Schermrotatie vastgezet",
"Home knop": "Home knop",
"Score scherm": "Score scherm",
"Score orientatie": "Score orientatie",
"jury": "jury",
"publiek": "publiek",
"onder": "onder",
"rechts": "rechts",
"links": "links",
"boven": "boven",
"Zoeken": "Zoeken",
"Ga naar": "Ga naar",
"Aktief": "Aktief",
"Inaktief": "Inaktief",
"Naam of nr": "Naam of nummer",
"Toestel": "Toestel",
"Blok": "Blok",
"Resultaten": "Resultaten",
"Oefeningen per blok": "Oefeningen per blok",
"PH Aan te maken wedstrijd": "naam voor aan te maken wedstrijd",
"TI Aan te maken wedstrijd": "alleen nodig indien nieuwe wedstrijd wordt aangemaakt",
"extra_aftrek_1": "Vallen op de mat na laatste sprong",
"extra_aftrek_2": "Vallen op de trampoline na laatste sprong",
"extra_aftrek_3": "Iets anders aanraken dan de trampolinemat",
"extra_aftrek_4": "Gebrek aan stabiliteit na laatste sprong",
"extra_aftrek_5": "Gebrek aan stabiliteit na laatste sprong",
"extra_aftrek_6": "Aanwijzingen van de trainer",
"extra_aftrek_7": "Te lange one-touch",
"extra_aftrek_8": "Inspringen >  61 sec",
"extra_aftrek_9": "Inspringen >  91 sec",
"extra_aftrek_10": "Inspringen > 121 sec",
"extra_aftrek_11": "Ontbrekende verpl. elementen 1e oefening (per el.)",
"extra_aftrek_12": "Teveel uitgevoerde sprongen",
};

localizedStrings['de_DE'] = {
"Taal naam": "Deutsch",
"Springer": "Turner",
"Oefening": "Kür",
"Jury": "Kampf-<br>richter",
"Aftrek": "Abzug",
"Score": "Ergebnis",
"ToF": "ToF",
"Sprong": "Sprung",
"Totaal": "Gesamt",
"Algemeen": "Generell",
"Aanmelden": "Registrieren",
"Upload": "Hochladen",
"Scorebord": "Anzeigetafel",
"Extra aftrek": "Extra Abzug (Istwert)",
"Instellingen": "Einstellungen",
"Algemene instellingen": "Allgemeine Einstellungen",
"Taal": "Sprache",
"OK": "OK",
"Annuleren": "Annulieren",
"Opsturen": "Hochladen",
"Wedstrijd aanmelden": "Wettkampf registrieren",
"Scorebord instellingen": "Anzeigetafel Einstellungen",
"Opgeslagen data": "Gespeicherte Daten",
"Wissen": "Löschen",
"Wedstrijd naam": "Wettkampf Name",
"Wedstrijd nummer": "Wettkampf Nummer",
"Wachtwoord": "Kennwort",
"Score server": "Ergebnis Server",
"Server log": "Server log",
"Jury naam": "Kampfrichter Name",
"Aanmaken": "Erstellen",
"Inloggen": "Einloggen",
"Uitloggen": "Ausloggen",
"Deelnemers": "Teilnehmer",
"Gebruik": "Nutzung",
"Automatische score upload": "Automatisch Ergebnisse hochladen",
"Start timer": "Start-Timer",
"uit": "aus",
"aan": "ein",
"knop": "knopf",
"automatisch": "automatisch",
"ja": "ja",
"nee": "nein",
"rechtshandig": "rechte Hand",
"Schermrotatie vastgezet": "Rotationssperre",
"Home knop": "Home-Knopf",
"Score scherm": "Anzeigetafel",
"Score orientatie": "Anzeige Orientation",
"jury": "Kampfrichter",
"publiek": "Zuschauer",
"onder": "Unten",
"rechts": "Rechts",
"links": "Links",
"boven": "Oben",
"Zoeken": "Suchen",
"Ga naar": "Gehe zu",
"Aktief": "Aktiv",
"Inaktief": "Inaktiv",
"Naam of nr": "Name oder Nummer",
"Toestel": "Gerät",
"Blok": "Gruppe",
"Resultaten": "Ergebnisse",
"Oefeningen per blok": "Küre pro Gruppe",
"PH Aan te maken wedstrijd": "Name für neue Wettkampf Erstellung",
"TI Aan te maken wedstrijd": "Nur erforderlich, wenn neuen Wettkampf erstellt wird",
"extra_aftrek_1": "Landing outside the trampoline bed after complete routine",
"extra_aftrek_2": "Falling on the trampolin bed after complete routine",
"extra_aftrek_3": "Touch anything other than the trampoline bed",
"extra_aftrek_4": "Not showing stability after complete routine",
"extra_aftrek_5": "Not showing stability after complete routine",
"extra_aftrek_6": "Instructions of spotters or coach",
"extra_aftrek_7": "Abuse of One-touch time limit",
"extra_aftrek_8": "First element initiated >  61 sec",
"extra_aftrek_9": "First element initiated >  91 sec",
"extra_aftrek_10": "First element initiated > 121 sec",
"extra_aftrek_11": "Missing required elements first routine (per el.)",
"extra_aftrek_12": "Additional elements",
};

localizedStrings['en_GB'] = {
"Taal naam": "English",
"Springer": "Gymnast",
"Oefening": "Exercise",
"Jury": "Judge",
"Aftrek": "Deduction",
"Score": "Score",
"ToF": "ToF",
"Sprong": "Jump",
"Totaal": "Total",
"Algemeen": "Common",
"Aanmelden": "Register",
"Upload": "Upload",
"Scorebord": "Scoreboard",
"Extra aftrek": "Extra deduction (real value)",
"Instellingen": "Settings",
"Algemene instellingen": "Common settings",
"Taal": "Language",
"OK": "OK",
"Annuleren": "Cancel",
"Opsturen": "Upload",
"Wedstrijd aanmelden": "Register competition",
"Scorebord instellingen": "Scoreboard settings",
"Opgeslagen data": "Stored data",
"Wissen": "Remove",
"Wedstrijd naam": "Competition name",
"Wedstrijd nummer": "Competition number",
"Wachtwoord": "Password",
"Score server": "Score server",
"Server log": "Server log",
"Jury naam": "Judge name",
"Aanmaken": "Create",
"Inloggen": "Login",
"Uitloggen": "Logout",
"Deelnemers": "Participants",
"Gebruik": "Usage",
"Automatische score upload": "Automatic score upload",
"Start timer": "Start timer",
"uit": "off",
"aan": "on",
"knop": "button",
"automatisch": "automatic",
"ja": "yes",
"nee": "no",
"rechtshandig": "right handed",
"Schermrotatie vastgezet": "Screen rotation locked",
"Home knop": "Home button",
"Score scherm": "Scoreboard",
"Score orientatie": "Score orientation",
"jury": "judges",
"publiek": "spectators",
"onder": "top",
"rechts": "right",
"links": "left",
"boven": "bottom",
"Zoeken": "Search",
"Ga naar": "Go to",
"Aktief": "Active",
"Inaktief": "Inactive",
"Naam of nr": "Name or number",
"Toestel": "Apparatus",
"Blok": "Group",
"Resultaten": "Results",
"Oefeningen per blok": "Exercises per group",
"PH Aan te maken wedstrijd": "Name for new competition creation",
"TI Aan te maken wedstrijd": "Only needed if new competition is created",
"extra_aftrek_1": "Landing outside the trampoline bed after complete routine",
"extra_aftrek_2": "Falling on the trampolin bed after complete routine",
"extra_aftrek_3": "Touch anything other than the trampoline bed",
"extra_aftrek_4": "Not showing stability after complete routine",
"extra_aftrek_5": "Not showing stability after complete routine",
"extra_aftrek_6": "Instructions of spotters or coach",
"extra_aftrek_7": "Abuse of One-touch time limit",
"extra_aftrek_8": "First element initiated >  61 sec",
"extra_aftrek_9": "First element initiated >  91 sec",
"extra_aftrek_10": "First element initiated > 121 sec",
"extra_aftrek_11": "Missing required elements first routine (per el.)",
"extra_aftrek_12": "Additional elements",
};

localizedStrings['fr_FR'] = {
"Taal naam": "Français",
"Springer": "Gymnaste",
"Oefening": "Épreuve",
"Jury": "Juge",
"Aftrek": "Déduction",
"Score": "Score",
"ToF": "ToF",
"Sprong": "Saut",
"Totaal": "Total",
"Algemeen": "Général",
"Aanmelden": "Inscripter",
"Upload": "Envoyer",
"Scorebord": "Écran",
"Extra aftrek": "Déduction additionnelle (valeur réelle)",
"Instellingen": "Réglages",
"Algemene instellingen": "Réglages généraux",
"Taal": "Langue",
"OK": "OK",
"Annuleren": "Annuler",
"Opsturen": "Envoyer",
"Wedstrijd aanmelden": "Inscription à la compétition",
"Scorebord instellingen": "Réglages écran",
"Opgeslagen data": "Données stockées",
"Wissen": "Effacer",
"Wedstrijd naam": "Nom de la compétition",
"Wedstrijd nummer": "Nombre de la compétition",
"Wachtwoord": "Mot de passe",
"Score server": "Score serveur",
"Server log": "Journal de serveur",
"Jury naam": "Nom de juge",
"Aanmaken": "Créer",
"Inloggen": "Connectez",
"Uitloggen": "Déconnectez",
"Deelnemers": "Participants",
"Gebruik": "Usage",
"Automatische score upload": "Envoyer des scores automatique",
"Start timer": "Start timer",
"uit": "non",
"aan": "oui",
"knop": "bouton",
"automatisch": "automatiquement",
"ja": "oui",
"nee": "non",
"rechtshandig": "droitier",
"Schermrotatie vastgezet": "Rotation de l'écran verrouillez",
"Home knop": "Bouton accueil",
"Score scherm": "Écran d’affichage",
"Score orientatie": "Rotation de l'écran",
"jury": "juge",
"publiek": "spectateurs",
"onder": "bas",
"rechts": "droit",
"links": "gauche",
"boven": "haut",
"Zoeken": "Rechercher",
"Ga naar": "Allez à",
"Aktief": "Active",
"Inaktief": "Inactive",
"Naam of nr": "Nom ou numéro",
"Toestel": "Appareil",
"Blok": "Groupe",
"Resultaten": "Resultats",
"Oefeningen per blok": "Exercices pour chaque groupe",
"PH Aan te maken wedstrijd": "naam voor aan te maken wedstrijd",
"TI Aan te maken wedstrijd": "alleen nodig indien nieuwe wedstrijd wordt aangemaakt",
"extra_aftrek_1": "Chute en dehors de la toile après un exercice complet",
"extra_aftrek_2": "Tomber sur la toile après un exercice complet",
"extra_aftrek_3": "Toucher les ressorts, les banquettes ou le cadre du trampoline",
"extra_aftrek_4": "Manque de stabilité après un exercice complet",
"extra_aftrek_5": "Manque de stabilité après un exercice complet",
"extra_aftrek_6": "Conseil donné par l'entraîneur, (pour chaque infraction)",
"extra_aftrek_7": "Dépasser la durée d'échauffement ",
"extra_aftrek_8": "Commencer premier élément >  61 sec",
"extra_aftrek_9": "Commencer premier élément >  91 sec",
"extra_aftrek_10": "Commencer premier élément > 121 sec",
"extra_aftrek_11": "Absence d’élément imposé dans le premier exercice (p/el.)",
"extra_aftrek_12": "Eléments supplémentaires",
};

localizedStrings['es_ES'] = {
"Taal naam": "Español",
"Springer": "Gimnasta",
"Oefening": "Paso",
"Jury": "Jurado",
"Aftrek": "Deducción",
"Score": "Nota",
"ToF": "ToF",
"Sprong": "Saltar",
"Totaal": "Total",
"Algemeen": "Genérico",
"Aanmelden": "Suscribirse",
"Upload": "Subir",
"Scorebord": "Marcador",
"Extra aftrek": "Deducción adicional (valor real)",
"Instellingen": "Configuración",
"Algemene instellingen": "Configuración general",
"Taal": "Idioma",
"OK": "OK",
"Annuleren": "Cancelar",
"Opsturen": "Subir",
"Wedstrijd aanmelden": "Registro concurso",
"Scorebord instellingen": "Configuración marcador",
"Opgeslagen data": "Los datos almacenados",
"Wissen": "Borrar",
"Wedstrijd naam": "Concurso nombre",
"Wedstrijd nummer": "Concurso número",
"Wachtwoord": "Contraseña",
"Score server": "Nota servidor",
"Server log": "Server log",
"Jury naam": "Nombre del Jurado",
"Aanmaken": "Crear",
"Inloggen": "Iniciar sesión",
"Uitloggen": "Desconectarse",
"Deelnemers": "Participantes",
"Gebruik": "Uso",
"Automatische score upload": "Nota subir automática",
"Start timer": "Temporizador",
"uit": "salida",
"aan": "en",
"knop": "botón",
"automatisch": "automática",
"ja": "sí",
"nee": "no",
"rechtshandig": "mano derecha",
"Schermrotatie vastgezet": "Rotación de pantalla bloqueado",
"Home knop": "Botón de inicio",
"Score scherm": "Marcador",
"Score orientatie": "Marcador orientación",
"jury": "jurado",
"publiek": "espectadores",
"onder": "arriba",
"rechts": "derecho",
"links": "izquierdo",
"boven": "bajo",
"Zoeken": "Buscar",
"Ga naar": "Ir a la",
"Aktief": "Activo",
"Inaktief": "Inactivo",
"Naam of nr": "Nombre o número",
"Toestel": "Aparato",
"Blok": "Grupo",
"Resultaten": "Resultados",
"Oefeningen per blok": "Pasa por grupo",
"PH Aan te maken wedstrijd": "Name for new competition creation",
"TI Aan te maken wedstrijd": "Only needed if new competition is created",
"extra_aftrek_1": "Landing outside the trampoline bed after complete routine",
"extra_aftrek_2": "Falling on the trampolin bed after complete routine",
"extra_aftrek_3": "Touch anything other than the trampoline bed",
"extra_aftrek_4": "Not showing stability after complete routine",
"extra_aftrek_5": "Not showing stability after complete routine",
"extra_aftrek_6": "Instructions of spotters or coach",
"extra_aftrek_7": "Abuse of One-touch time limit",
"extra_aftrek_8": "First element initiated >  61 sec",
"extra_aftrek_9": "First element initiated >  91 sec",
"extra_aftrek_10": "First element initiated > 121 sec",
"extra_aftrek_11": "Missing required elements first routine (per el.)",
"extra_aftrek_12": "Additional elements",
};

localizedStrings['ru_RU'] = {
"Taal naam": "Русский",
"Springer": "Прыгун",
"Oefening": "Упражнение",
"Jury": "Жюри",
"Aftrek": "вычет",
"Score": "результат",
"Sprong": "Прыжок",
"Totaal": "Общий результат",
"Algemeen": "В общем",
"Aanmelden": "Записаться",
"Upload": "Загрузить",
"Scorebord": "Табло",
"Extra aftrek": "Дополнительные вычет",
"Instellingen": "настройки",
"Algemene instellingen": "Общие настройки",
"Taal": "Язык",
"Annuleren": "Отменить",
"Opsturen": "Отправить",
"Wedstrijd aanmelden": "Записаться на соревнование",
"Scorebord instellingen": "Турнирная таблица настройки",
"Opgeslagen data": "Сохраненные данные",
"Wissen": "Стирать",
"Wedstrijd naam": " Название соревнования",
"Wedstrijd nummer": "Номер соревнования",
"Wachtwoord": "Пароль",
"Score server": "Cервер результатов",
"Server log": "Сервер журнала",
"Jury naam": "Имя жюри",
"Aanmaken": "Создать",
"Inloggen": "входить",
"Uitloggen": "выходить",
"Deelnemers": "Участники",
"Start volgorde": "Стартовый порядок",
"Gebruik": "Использование",
"Automatische score upload": "Автоматически загружать результаты",
"Start timer": "Секундомер",
"uit": "выключен",
"aan": "включен",
"knop": "Кнопка",
"automatisch": "Автоматический",
"ja": "да",
"nee": "нет",
"rechtshandig": "правша",
"linkshandig": "левша",
"Schermrotatie vastgezet": "вращение экрана заблокировано",
"Home knop": "Главная кнопка",
"Score scherm": "Экран с результатами",
"Score orientatie": "ориентацонные результаты",
"jury": "Жюри",
"publiek": "зрители",
"onder": "под",
"rechts": "право",
"links": "лево",
"boven": "Топ",
"Zoeken": "поиск",
"Ga naar": "Перейти к",
"Aktief": "Активный",
"Inaktief": "Неактивный",
"Naam of nr": "Название или номер",
"Toestel": "снаряд",
"Blok": "Блок",
"Resultaten": "Результаты",
"Kleur": "Цвет",
"Vertaling": "Перевод",
"Alles opsturen": "Все отправить",
"Download scores": "Скачать оценки",
"Aantal oefeningen": "Количество упражнений",
"Maximum aantal sprongen": "Максимальное количество прыжков",
"PH Aan te maken wedstrijd": "названия соревнования",
"TI Aan te maken wedstrijd": "толко нужно когда новое соревнование",
"extra_aftrek_1": "Упасть на мат после последнего прыжка",
"extra_aftrek_2": "Упасть на батут после последнего прыжка",
"extra_aftrek_3": "Коснуться чего-то другого, кроме сетки батута",
"extra_aftrek_4": "Недостаток стабильности после заключительного прыжка",
"extra_aftrek_5": "Недостаток стабильности после заключительного прыжка",
"extra_aftrek_6": "Указания тренера",
"extra_aftrek_7": "Слишком дольгий one-touch",
"extra_aftrek_8": "разминка >  61 сек",
"extra_aftrek_9": "разминка >  91 сек",
"extra_aftrek_10": "разминка > 121 сек",
"extra_aftrek_11": "Недостающие в 1ом упражнение элементы",
"extra_aftrek_12": "Слишком много выполненных прыжков",
};
